{{ if .Values.argocd.randomLogger.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: random-logger
  namespace: argocd
spec:
  project: default
  destination:
    namespace: random-logger
    server: https://kubernetes.default.svc
  source:
    path: random-logger/helm
    repoURL: 'https://github.com/erickfranca/argo-gitops.git'
    targetRevision: feat/day2
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{ end }}